{
 "title": "URL Shortener Metrics",
 "tags": [
  "url-shortener",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Количество переходов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(links_clicks_total[1m])) * 60",
     "legendFormat": "clicks / min"
    }
   ]
  },
  {
   "title": "Количество созданных ссылок в минуту",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(links_total[1m])) * 60",
     "legendFormat": "created / min"
    }
   ]
  },
  {
   "title": "Среднее время ответа на редирект",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{application=\"shortener-service\", uri=\"/{shortCode}\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"shortener-service\", uri=\"/{shortCode}\"}[5m]))",
     "legendFormat": "avg redirect latency"
    }
   ]
  },
  {
   "title": "outbox.pending.count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "outbox_pending_count", "legendFormat": "pending" }
   ]
  }
 ]
}